### ISSUE TITLE
birthday.rb solution is not accurate

### ISSUE THREAD

**Issue by dnj547** [learn-co-curriculum/hash-iteration#15]
The birthday.rb file in the solution branch is not accurate. In this file, the happy_birthday method includes an unnecessary comma. Additionally, the "bonus" (age_appropriate_birthday method) is not mentioned in the README.

**Comment by Crankums** [comment]
Not only is the bonus challenge (age_related_birthday method) not present in the README, it's also not present anywhere in the spec files. If there was an additional install to run, no instruction is present anywhere on the learn.co site or the IDE folder.

**Comment by drakeltheryuujin** [comment]
Hi @dnj547,

Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this
issue. 💙
