### ISSUE TITLE
Bonus content missing 

### ISSUE THREAD

**Issue by sharkham** [learn-co-curriculum/hash-iteration#16]
"BONUS: In spec/birthday_spec.rb, one test is pending, meaning it is not currently counting towards lab completion. After passing all the other tests, if you would like to challenge yourself a bit more, go into spec/birthday_spec.rb and remove pending from the beginning of the second test. Run learn to see that the test is now failing rather than listed as pending, and use the test message to create a new method, age_appropriate_birthday." 

<-- This wasn't in spec so this text should probably be removed from the end of the lesson!

**Comment by drakeltheryuujin** [comment]
Hi @sharkham,

Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this
issue. 💙
