### ISSUE TITLE
Test won't pass although code is correct

### ISSUE THREAD

**Issue by ZumbaIdol** [learn-co-curriculum/hash-iteration#18]
I both typed and copied the code for this code along but it won't pass, though the readme states that it should...

`def select_winner(passengers)
 winner = ""
  passengers.each do |suite, name|
    if suite == :suite_a && name.start_with?("A")
      winner = name
   end
end

winner`

**Comment by maxwellbenton** [comment]
Hi @ZumbaIdol,

I've taken a look at this lesson and run through the code-along instructions. I was able to get the tests to pass, however, it looks like the tests were out of order compared to the instructions. I've updated the lesson's instructions and tests and confirmed that the code snippet in the readme passes the #select_winner test and made it clearer that this should only pass the _first_ of the three tests in this code-along.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by ZumbaIdol** [comment]
Thank you for your help and time spent on this issue.

D. Foote
