### ISSUE TITLE
Hash Iteration with Each

### ISSUE THREAD

**Issue by ayo3able** [learn-co-curriculum/hash-iteration#20]
The instructions were unclear. The first method that you should copy and paste needs another "end" at the end of the method. and the instructions never tell you that your second method should go in another file.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
