### ISSUE TITLE
Duplicate Lab?

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/hash-iteration#5]
There is a _Hash Iteration_ lab followed by a _Hash Iteration - Each_ lab both of which are the same. Hash Iteration does not have the option to be opened through learn, but Hash Iteration - Each can.

When I clicked "next lesson" on the Hash Iteration - Each lab it too displayed an empty grey circle indicating I had not completed it.

I'm sure this is not intentional, just letting y'all know.

**Comment by deniznida** [comment]
@AnnJohn

**Comment by AnnJohn** [comment]
thanks, removed the first lab. This is in the public pre-work track.
