### ISSUE TITLE
Not able to fork this one on Learn

### ISSUE THREAD

**Issue by sev2109** [learn-co-curriculum/hash-iteration#9]
Hello!
This one did not give us an option to clone the repo from the Nitrous button on Learn. I was able to do so through github, but it could be confusing for others who come along expecting that Nitrous button. Also, the instructions say: "Open up this repo in your text editor to get started. Follow along with the instructions below to get your tests passing."
There is no "tests passing" button on this lab in Learn -- it presents itself as just a readme.

SV

**Comment by AnnJohn** [comment]
Hi @sev2109 thanks for raising the issue. This looks like a bug, so could you actually file a bug report? In Learn, when you hover over your profile picture you'll see the option to File a Bug Report. Thanks!
